# Generated by Django 3.0 on 2021-11-09 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('photo', models.ImageField(upload_to='customers')),
                ('phone', models.CharField(max_length=20)),
                ('about', models.TextField()),
                ('is_owing', models.BooleanField(default=False)),
            ],
        ),
    ]
