# Generated by Django 3.0 on 2021-11-24 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20211124_0351'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
