# Generated by Django 3.0 on 2021-11-24 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_remove_category_number_of_products'),
        ('customers', '0003_customer_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='products',
            field=models.ManyToManyField(null=True, related_name='customer_products', to='products.Product'),
        ),
    ]
