# Generated by Django 3.0 on 2021-11-25 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_remove_category_number_of_products'),
        ('sales', '0004_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='product',
        ),
        migrations.AddField(
            model_name='sale',
            name='product',
            field=models.ManyToManyField(to='products.Product'),
        ),
    ]
