# Generated by Django 3.0 on 2021-11-25 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_auto_20211125_0414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='product',
            new_name='positions',
        ),
    ]
