# Generated by Django 3.0 on 2021-11-25 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_auto_20211125_0419'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=50)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('total_sale_price', models.FloatField(default=0.0)),
                ('date_created', models.DateTimeField(blank=True)),
                ('positions', models.ManyToManyField(to='sales.Position')),
            ],
        ),
    ]
