# Generated by Django 3.0 on 2021-11-25 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_dailysale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailysale',
            name='total_sale_price',
        ),
    ]
