# Generated by Django 3.0 on 2021-12-05 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_remove_dailysale_total_sale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='created',
            field=models.DateField(blank=True),
        ),
    ]
