# Generated by Django 3.0 on 2021-12-05 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_auto_20211125_0313'),
        ('sales', '0010_auto_20211205_0604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='custormer',
        ),
        migrations.AddField(
            model_name='position',
            name='custormer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.Customer'),
        ),
    ]
