# Generated by Django 3.0 on 2021-12-05 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_auto_20211205_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='position_id',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
