# Generated by Django 3.0 on 2021-11-10 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='reorder_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
