# Generated by Django 3.0 on 2021-11-15 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20211115_0442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='quantity',
            new_name='purchase_quantity',
        ),
    ]
