# Generated by Django 3.0 on 2021-11-15 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20211115_0517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='created',
            new_name='purchase_created',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='updated',
            new_name='purchase_updated',
        ),
    ]
