# Generated by Django 3.0 on 2021-11-23 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_store'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category_name',
        ),
    ]
