# Generated by Django 3.0 on 2021-11-23 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20211123_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='number_of_products',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
