# Generated by Django 3.0 on 2021-11-23 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_category_number_of_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='number_of_products',
        ),
    ]
